name: Run tests by FPC

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install FPC
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: lazarus
          version: 1.0
      - name: Checkout
        uses: actions/checkout@v4
      - name: build
        working-directory: ./src/fpc
        run: |
          make all
      - name: run tests
        working-directory: ./src/fpc
        run: |
          make test
